[build]
  functions = "netlify/functions"  # Keep as is
  publish = "public"              # Changed from "." to "public"

[dev]
  functions = "netlify/functions"
  publish = "public"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200